---
- name: Icinga2 master setup
  shell: icinga2 node setup --master creates=/var/lib/icinga2/ca/ca.key
  notify: restart icinga

- name: enable api
  shell: icinga2 feature enable api creates=/etc/icinga2/features-enabled/api.conf
  notify: restart icinga

- name: create zones.d config dirs
  file:
   path: "/etc/icinga2/zones.d/{{ item }}"
   state: directory
   owner: "{{ icinga_user }}"
   group: "{{ icinga_user }}"
   mode: "0755"
  with_items:
    - global-templates
    - global-templates/notifications
    - global-templates/checks
    - master

- name: put config templates
  template:
    src: "{{ item }}.j2"
    dest: "/etc/icinga2/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - zones.conf
    - constants.conf
    - icinga2.conf
  notify: restart icinga

- name: put global templates
  template:
    src: "{{ item.src }}"
    dest: "/etc/icinga2/zones.d/global-templates/{{ item.path }}"
    owner: "{{ icinga_user }}"
    group: "{{ icinga_user }}"
    mode: "0644"
  with_filetree:
    - ../templates/global-templates/
  when: item.state == 'file'
  notify: restart icinga

- name: create icinga2 database
  mysql_db: name={{ idodbname }} state=present
  register: icingadb

- name: create icinga2 database user
  mysql_user: name={{ idodbuser }} password={{ idodbpass }} priv={{ idodbname }}.*:ALL append_privs=true state=present

- name: load database schema
  mysql_db: state=import name={{ idodbname }} target=/usr/share/icinga2-ido-mysql/schema/mysql.sql
  when: icingadb.changed

- name: put ido-mysql.conf
  template: src=ido-mysql.conf.j2 dest=/etc/icinga2/features-available/ido-mysql.conf
  notify: restart icinga

- name: enable ido-mysql feature for web
  shell: icinga2 feature enable ido-mysql creates=/etc/icinga2/features-enabled/ido-mysql.conf
  notify: restart icinga
