---
- name: create slack config dir
  file:
    path: "/etc/icinga2/zones.d/global-templates/notifications/slack"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: put slack Icinga config templates
  template:
    src: "notifications/slack/{{ item }}.j2"
    dest: "/etc/icinga2/zones.d/global-templates/notifications/slack/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - slack-notifications-user-configuration.conf
  notify: restart icinga

- name: put slack Icinga config files
  copy:
    src: "{{ item }}"
    dest: /etc/icinga2/zones.d/global-templates/notifications/slack/
    owner: "root"
    group: "root"
    mode: "0644"
  with_fileglob:
    - notifications/slack/*.conf
