---
- name: start varnish
  service:
    name: varnish
    state: started
    enabled: yes

- name: restart varnish
  service:
    name: varnish
    state: restarted
    enabled: yes

- name: reload systemd and varnish
  systemd:
    state: restarted
    daemon_reload: yes
    name: varnish

- name: reload apache2
  service:
    name: apache2
    state: reloaded
    enabled: yes
