---
- name: reload php5
  service:
    name: php5-fpm
    state: reloaded
    enabled: yes

- name: reload php7.0
  service:
    name: php7.0-fpm
    state: reloaded
    enabled: yes

- name: reload php7.1
  service:
    name: php7.1-fpm
    state: reloaded
    enabled: yes

- name: reload php7.2
  service:
    name: php7.2-fpm
    state: reloaded
    enabled: yes

- name: reload php7.3
  service:
    name: php7.3-fpm
    state: reloaded
    enabled: yes

- name: reload php7.4
  service:
    name: php7.4-fpm
    state: reloaded
    enabled: yes

- name: reload php8.0
  service:
    name: php8.0-fpm
    state: reloaded
    enabled: yes

- name: reload php8.1
  service:
    name: php8.1-fpm
    state: reloaded
    enabled: yes

- name: reload php8.2
  service:
    name: php8.2-fpm
    state: reloaded
    enabled: yes

- name: reload apache2
  service:
    name: apache2
    state: reloaded
    enabled: yes

- name: reload nginx
  service:
    name: nginx
    state: reloaded
    enabled: yes

- name: restart solr-jetty
  service:
    name: jetty
    state: restarted
    enabled: yes

- name: restart solr-jetty8
  service:
    name: jetty8
    state: restarted
    enabled: yes

- name: reload ufw
  ufw:
    state: reloaded
