---
roles:
  - src: fiaasco.locale
  - src: fiaasco.chrony
  - src: fiaasco.mariadb
    version: v0.9.2
  - src: fiaasco.php7
    version: v1.0.1
  - src: fiaasco.solr
    version: v0.0.2

collections:
  - name: fiaasco.icinga2
    version: v1.0.6
