---
roles:
  - src: fiaasco.chrony
  - src: fiaasco.mariadb
    version: '0.8.2'
  - src: fiaasco.apache2
  - src: fiaasco.php7
  - src: fiaasco.solr
    version: 'v0.0.1'

collections:
  - name: fiaasco.icinga2
    version: '1.0.5'
