---
- name: create services directories
  template:
    dest: "/etc/icinga2/zones.d/global-templates/checks/{{ item.path }}"
    state: directory
    owner: "{{ icinga_user }}"
    group: "{{ icinga_user }}"
    mode: "{{ item.mode }}"
  with_filetree:
    - ../templates/checks/
  when: item.state == 'directory'
  delegate_to: "{{ groups.icingaservers|first }}"
  notify: restart master icinga2

- name: copy service definitions to Icinga primary master
  template:
    src: "{{ item.src }}"
    dest: "/etc/icinga2/zones.d/global-templates/checks/{{ item.path }}"
    owner: "{{ icinga_user }}"
    group: "{{ icinga_user }}"
    mode: "{{ item.mode }}"
  with_filetree:
    - ../templates/checks/
  when: item.state == 'file'
  delegate_to: "{{ groups.icingaservers|first }}"
  notify: restart master icinga2
