# -*- mode: ruby -*-
# vi: set ft=ruby :
#

DEBIAN_BOX = "debian82"
DEBIAN_BOX_URL = "http://repo.werus.be/vagrant/debian-8.2-amd64.box"


Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end

  config.ssh.insert_key = false

  config.vm.define "debian820" do |v|
    v.vm.box = DEBIAN_BOX
    v.vm.box_url = DEBIAN_BOX_URL
    v.vm.hostname = "debian820"
    v.vm.network :private_network, ip: "192.168.131.190"
    v.vm.network :forwarded_port, guest: 22, host: 10190, id: 'ssh'
    v.hostsupdater.aliases = [ "www.vhost1.com", "www.vhost2.com", "www.vhost3.com" ]
  end

  config.vm.define "debian821" do |v|
    v.vm.box = DEBIAN_BOX
    v.vm.box_url = DEBIAN_BOX_URL
    v.vm.hostname = "debian821"
    v.vm.network :private_network, ip: "192.168.131.191"
    v.vm.network :forwarded_port, guest: 22, host: 10191, id: 'ssh'
    v.hostsupdater.aliases = [ "www.svhost1.com", "www.svhost2.com", "www.svhost3.com" ]
  end

  config.vm.define "debian822" do |v|
    v.vm.box = DEBIAN_BOX
    v.vm.box_url = DEBIAN_BOX_URL
    v.vm.hostname = "debian822"
    v.vm.network :private_network, ip: "192.168.131.192"
    v.vm.network :forwarded_port, guest: 22, host: 10192, id: 'ssh'
    v.vm.provision :ansible do |ansible|
      ansible.inventory_path = "inventory/"
      ansible.playbook = "../../playbooks/lamp.yml"
      ansible.sudo = "true"
      ansible.host_key_checking = "false"
      ansible.limit = 'all'
    end
  end

end

