---
- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0775"
  with_items:
    - /var/www/acme
    - /var/www/sites
    - /var/www/sites/adminhost

- name: install apache webserver
  apt:
    name:
      - apache2
      - liblwp-useragent-determined-perl
    state: present
    cache_valid_time: 3600
    update_cache: yes
  notify: start apache2

- name: put ssl.conf
  template:
    src: ssl.conf.j2
    dest: /etc/apache2/mods-available/ssl.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload apache2

- name: configure apache webserver
  template:
    src: apache2.conf.j2
    dest: /etc/apache2/apache2.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart apache2

- name: put apache ports.conf
  template:
    src: apache-ports.conf.j2
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart apache2

- name: put apache security config
  template:
    src: security.conf
    dest: /etc/apache2/conf-available/security.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart apache2

- name: disable modules (impossible with apache2_module till ansible 2.3)
  shell: a2dismod {{ item }} removes=/etc/apache2/mods-enabled/{{ item }}.load
  with_items:
    - php7.0
    - mpm_prefork
    - mpm_event
  notify: restart apache2

- name: enable mpm_worker (impossible with apache2_module till ansible 2.3)
  shell: a2enmod mpm_worker creates=/etc/apache2/mods-enabled/mpm_worker.load
  notify: restart apache2

- name: enable modules
  apache2_module: name={{ item }} state=present
  with_items:
    - actions
    - deflate
    - rewrite
    - ssl
    - headers # required for HSTS
  notify: reload apache2

- name: enable httpd
  apache2_module:
    name: "http2"
    state: present
  notify: reload apache2
  when: inventory_hostname not in groups.nginx|default([])

- name: Apache | Enable mod_remoteip if required
  apache2_module:
    name: remoteip
    state: present
  when: varnish_required == True

- name: create temporary list to add libapache2-mod- to the package names
  set_fact:
    temp_list: "{% for item in apache_extra_modules %}libapache2-mod-{{ item }} {% endfor %}"
  when: apache_extra_modules is defined

- set_fact:
    modules_list: "{{ temp_list.split() }}"
  when: apache_extra_modules is defined

- name: Apache | Install extra modules
  apt:
    name: "{{ modules_list }}"
    state: present
  when: apache_extra_modules is defined

- name: Apache | Enable extra modules
  apache2_module:
    name: "{{ item|replace('-','_') }}"
    state: present
  with_items: apache_extra_modules
  when: apache_extra_modules is defined
  notify: reload apache2

- name: create empty index.html
  copy:
    src: index.html
    dest: /var/www/sites/adminhost/index.html
    owner: root
    group: root
    mode: "0644"

- name: add our hostname-vhost config
  template:
    src: admin-vhost.conf.j2
    dest: /etc/apache2/sites-available/admin-vhost.conf
    owner: root
    group: root
    mode: "0644"

- name: Enable admin vhost
  shell: a2ensite admin-vhost.conf
  args:
    creates: /etc/apache2/sites-enabled/admin-vhost.conf
  notify: reload apache2

- name: disable default default site
  shell: a2dissite 000-default
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: reload apache2

- name: enable logrotation for /var/www/apache2/
  copy:
    src: logrotate.apache24
    dest: /etc/logrotate.d/apache2
    owner: root
    group: root
    mode: "0644"

- name: copy over htpasswd for fiaas.co
  template:
    src: fiaasco.htpasswd
    dest: /etc/apache2/fiaasco.htpasswd
    owner: root
    group: root
    mode: "0644"
  when: groups.infra is defined and inventory_hostname in groups.infra

- name: create extra-conf dir
  file:
    dest: /etc/apache2/extra.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: create admin vhost includes dir
  file:
    dest: /etc/apache2/admin.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: flush handlers to activate changes we need now
  meta: flush_handlers

- import_tasks: certificates.yml

- name: add our hostname-vhost-ssl config
  template:
    src: admin-vhost-ssl.conf.j2
    dest: /etc/apache2/sites-available/admin-vhost-ssl.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload apache2
  when: not nginx_required | default(False)

- name: Enable https admin vhost
  shell: a2ensite admin-vhost-ssl.conf
  args:
    creates: /etc/apache2/sites-enabled/admin-vhost-ssl.conf
  when: not nginx_required | default(False)
  notify: reload apache2

- name: Disable https admin vhost when nginx is used to terminate ssl
  shell: a2dissite admin-vhost-ssl.conf
  args:
    removes: /etc/apache2/sites-enabled/admin-vhost-ssl.conf
  when: nginx_required | default(False)
  notify: reload apache2
