---
- name: request ticket on master
  shell: "icinga2 pki ticket --cn {{ ansible_fqdn }} --salt {{ ticketsalt }}"
  args:
    creates: /etc/icinga2/zones.conf.orig
  register: ticket

- name: prepare pki directory
  file:
    path: /var/lib/icinga2/certs
    state: directory
    owner: nagios
    group: nagios
    mode: "0755"

- name: Generate a new local self-signed certificate.
  shell: "icinga2 pki new-cert --cn {{ ansible_fqdn }} --key /var/lib/icinga2/certs/{{ ansible_fqdn }}.key --cert /var/lib/icinga2/certs/{{ ansible_fqdn }}.crt"
  args:
    creates: /var/lib/icinga2/certs/{{ ansible_fqdn }}.crt
  notify: restart icinga2

- name: Request the master certificate from the master host and store it as trusted-master.crt
  shell: "icinga2 pki save-cert --key /var/lib/icinga2/certs/{{ ansible_fqdn }}.key --cert /var/lib/icinga2/certs/{{ ansible_fqdn }}.crt --trustedcert /var/lib/icinga2/certs/trusted-master.crt --host {{ item }}"
  args:
    creates: /var/lib/icinga2/certs/trusted-master.crt
  with_items: "{{ groups.icingaservers|first }}"
  notify: restart icinga2

- name: Continue with the additional node setup steps
  shell: "icinga2 node setup --ticket {{ ticket.stdout }} --endpoint {{ item }},{{ item }},5665 --zone {{ ansible_fqdn }} --master_host {{ item }} --master_zone master --trustedcert /var/lib/icinga2/certs/trusted-master.crt --accept-config --accept-commands"
  args:
    creates: /etc/icinga2/zones.conf.orig
  with_items: "{{ groups.icingaservers|first }}"
  notify: restart icinga2

- name: enable feature api
  shell: icinga2 feature enable api
  args:
    creates: /etc/icinga2/features-enabled/api.conf
  notify: restart icinga2

- name: put config templates
  template:
    src: "{{ item }}.j2"
    dest: "/etc/icinga2/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart icinga2
  with_items:
    - icinga2.conf
