---
- name: install packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - icinga2
    - monitoring-plugins
  notify: restart icinga2

#- name: allow icinga servers to icinga client port through external ip
#  ufw:
#    rule: allow
#    interface: "{{ public_interface }}"
#    direction: in
#    proto: tcp
#    src: "{{ hostvars[item].external_ip }}"
#    to_port: 5665
#  with_items: "{{ groups.icingaservers }}"
#  notify: reload ufw
#  when: monitoring_over_ssh == False and hostvars[item].external_ip is defined
