---
- name: databases | create databases
  mysql_db:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ databases }}"
  when: not item.delete|default(False)

- name: databases | grant local users to the databases
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    priv: "{{ item.name }}.*:ALL"
    append_privs: true
    state: present
  with_items: "{{ databases }}"
  when: item.ip is not defined and not item.delete|default(False)

- name: databases | grant remote users to the databases
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    host: "%"
    priv: "{{ item.name }}.*:ALL"
    state: present
    append_privs: yes
  with_items: "{{ databases }}"
  when: item.ip is defined and not item.delete|default(False)

- name: databases | add ufw rules for these special databases
  ufw:
    rule: allow
    interface: "{{ public_interface }}"
    direction: in
    src: "{{ item.1 }}"
    proto: tcp
    to_port: 3306
  with_subelements:
    - "{{ databases }}"
    - ip
    - flags:
      skip_missing: true
  when: not item.0.delete|default(False)
  notify: reload ufw
