---
- name: put vhost ssl request template
  template:
    src: request-vhost.sh
    dest: /root/ssl/request-{{ item.url }}.sh
    owner: root
    group: root
    mode: "0700"
  with_items: "{{ vhosts }}"
  when: not item.delete|default(False)

- name: Update webroot in existing configs when acme_config_update is set
  lineinfile:
    dest: "/root/.acme.sh/{{ item.url }}/{{ item.url }}.conf"
    regexp: '^Le_Webroot='
    line: 'Le_Webroot=/var/www/acme'
  with_items: "{{ vhosts }}"
  when: >
    not item.delete|default(False) and
    item.ssl|default(False) == 'letsencrypt' and
    acme_config_update|default(False)
