---
- name: Include distribution specific vars
  include_vars: "{{ ansible_distribution_release }}.yml"

- import_tasks: users.yml
  tags:
    - users

- import_tasks: directories.yml
  tags:
    - directories

- import_tasks: symlinks.yml
  tags:
    - symlinks

- import_tasks: useraccess.yml
  tags:
    - authorized_keys
    - users

- import_tasks: phppools.yml
  tags:
    - php
    - phppools

- import_tasks: letsencrypt.yml
  tags:
    - vhosts
    - letsencrypt

- import_tasks: vhosts.yml
  tags:
    - vhosts

- import_tasks: acls.yml
  tags:
    - acls

- import_tasks: databases.yml
  tags:
    - databases

- import_tasks: "solr-shared.yml"
  when: solr_required|bool
  tags:
    - solr

- import_tasks: "solr-cores.yml"
  when: solr_required|bool
  tags:
    - solr

- import_tasks: logrotate.yml
  tags:
    - vhosts
    - logrotate
