---
- name: useraccess | configure authorized_keys for users
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
    state: present
  with_subelements:
    - "{{ users }}"
    - authorized_keys
    - skip_missing: True
  when: not item.delete|default(False)
  tags: ['users','authorized_keys']

- name: useraccess | get vm_owner ssh keys (can be a system or normal user)
  set_fact:
    vm_owner: "{{ item }}"
  when: >
    vm_owner is defined
    and item.name == vm_owner
  with_items:
    - "{{ systemusers }}"
    - "{{ users }}"

- name: useraccess | configure vm owner authorized_keys in shared_server users
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
    state: present
  with_nested:
    - "{{ users }}"
    - "{{ vm_owner.authorized_keys }}"
  when:
    vm_owner.authorized_keys is defined
    and not item.delete|default(False)
  tags: ['users','authorized_keys']
