---
- name: useraccess | configure authorized_keys for users
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
    state: present
  with_subelements:
    - "{{ users }}"
    - authorized_keys
    - skip_missing: True
  when: not item.0.delete|default(False)

- name: useraccess | configure vm owner authorized_keys in shared_server users
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
    state: present
  with_nested:
    - "{{ users }}"
    - "{{ owners[vm_owner].authorized_keys }}"
  when:
    vm_owner is defined
    and owners[vm_owner].authorized_keys is defined
    and not item.0.delete|default(False)
