---
phptools_pkgs:
  - ghostscript
  - git
  - imagemagick
  - libjpeg-progs
  - optipng
  - patch

composer_version: "1.3.2"
composer_url: "https://getcomposer.org/download/{{ composer_version }}/composer.phar"
composer_checksum: "sha256:6a4f761aa34bb69fca86bc411a5e9836ca8246f0fcd29f3804b174fee9fb0569"
