---
# This file contains a few steps to migrate from Icinga 2.7 on debmon repos to
# to Icinga 2.8 on the Icinga repo's with a new directory structure for the monitored hosts
# config.
# It's only necessary for the migration and will be removed in the future

- name: remove old directories (if this is changed, you have to update ALL monitored hosts config!)
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/icinga2/zones.d/master/checks
    - /etc/icinga2/zones.d/master/notifications
    - /etc/icinga2/zones.d/master/hosts
  when: inventory_hostname in groups.icingaservers

- name: check if this host was earlier installed
  stat:
    path: /etc/icinga2/pki/{{ inventory_hostname }}.key
  register: icinga_installed

- name: move icinga certificates for 2.8 migration
  shell: mv /etc/icinga2/pki/ /var/lib/icinga2/certs/
  args:
    creates: /var/lib/icinga2/certs/{{ inventory_hostname }}.key
  when: icinga_installed.stat.exists | default(False)
  notify: restart icinga2

- name: move ca to standard file for 2.8 migration
  shell: mv /var/lib/icinga2/certs/trusted-master.crt /var/lib/icinga2/certs/ca.crt
  args:
    creates: /var/lib/icinga2/certs/ca.crt
  when: icinga_installed.stat.exists | default(False)
  notify: restart icinga2

- name: remove debmon apt key
  apt_key:
    id: "{{ item }}"
    state: absent
  with_items:
    - 7E55BD75930BB3674BFD6582DC0EE15A29D662D2
    - 29D662D2

- name: remove debmon repo
  apt_repository:
    repo: "deb http://debmon.org/debmon debmon-{{ ansible_distribution_release }} main"
    state: absent

- name: update api.conf for Icinga 2.8
  lineinfile:
    dest: /etc/icinga2/features-available/api.conf
    state: absent
    regexp: '{{ item }}'
  notify: restart icinga2
  with_items:
    - '^  cert_path ='
    - '^  key_path ='
    - '^  ca_path ='

- name: verify if global-templates zone exists in zones.conf
  lineinfile:
    dest: /etc/icinga2/zones.conf
    line: 'object Zone "global-templates" {'
    state: present
  check_mode: yes
  when: icinga_installed.stat.exists | default(False)
  register: zones

- name: add global zones in zones.conf
  blockinfile:
    dest: /etc/icinga2/zones.conf
    insertafter: EOF
    content: |
      object Zone "global-templates" {
        global = true
      }

      object Zone "director-global" {
        global = true
      }
  notify: restart icinga2
  when: zones | changed | default(False)
