---
- name: remove deleted vhost ssl request script
  file:
    path: "/root/ssl/request-{{ item.url }}.sh"
    state: absent
  with_items: "{{ vhosts }}"
  when: item.delete|default(False)
  tags: ['vhosts', 'letsencrypt']

- name: remove deleted vhost acme.sh conf (keep certs)
  shell: "/root/.acme.sh/acme.sh --remove -d {{ item.url }}"
  args:
    creates: "/root/.acme.sh/{{ item.url }}/{{ item.url }}.conf.removed"
