---
- import_tasks: acls.yml
  tags:
    - acls

- import_tasks: phppools.yml
  tags:
    - php
    - phppools

- import_tasks: letsencrypt.yml
  tags:
    - letsencrypt
    - vhosts

- import_tasks: vhosts.yml
  tags:
    - vhosts

- import_tasks: logrotate.yml
  tags:
    - vhosts

- import_tasks: "solr-shared.yml"
  when: solr_required == True
  tags:
    - solr

- import_tasks: "solr-cores.yml"
  when: solr_required == True
  tags:
    - solr

- name: flush handlers before we remove the basic resources
  meta: flush_handlers

- import_tasks: databases.yml
  tags:
    - databases

- import_tasks: symlinks.yml
  tags:
    - symlinks

- import_tasks: directories.yml
  tags:
    - directories

- import_tasks: useraccess.yml
  tags:
    - authorized_keys
    - users

- import_tasks: users.yml
  tags:
    - users
