---
- name: remove fpm-pool.d file for defined pools
  file:
    path: "/etc/php5/fpm/pool.d/{{ item.name }}.conf"
    state: absent
  with_items: "{{ phppools }}"
  notify: reload php5
  when: >
    item.delete|default(False)
    and ansible_distribution == 'Debian'
    and ansible_distribution_major_version < '9'

- name: remove fpm-pool.d file for defined pools
  file:
    path: "/etc/php/{{ item.version|default('7.0') }}/fpm/pool.d/{{ item.name }}.conf"
    state: absent
  with_items: "{{ phppools }}"
  notify: reload php{{ item.version|default('7.0') }}
  when: >
    item.delete|default(False)
    and ansible_distribution == 'Debian'
    and ansible_distribution_major_version >= '9'
