---
- name: remove fpm-pool.d file for php7 defined pools
  file:
    path: "/etc/php/{{ item.1 }}/fpm/pool.d/{{ item.0.name }}.conf"
    state: absent
  with_nested:
    - "{{ phppools }}"
    - "{{ php7_versions|default([php_distro_version]) }}"
  notify: reload php{{ item.0.version|default(php_distro_version) }}
  when: item.0.delete|default(false)

- name: remove fpm-pool.d file for php8 defined pools
  file:
    path: "/etc/php/{{ item.1|default(php_distro_version) }}/fpm/pool.d/{{ item.0.name }}.conf"
    state: absent
  with_nested:
    - "{{ phppools }}"
    - "{{ php8_versions|default([php_distro_version]) }}"
  notify: reload php{{ item.0.version|default(php_distro_version) }}
  when: item.0.delete|default(false)
