---
- name: vhosts | remove certificates directory for selfsigned/commercial
  file: dest=/etc/ssl/{{ item.url }} state=absent
  with_items: "{{ vhosts }}"
  when: item.ssl|default(False) != "letsencrypt" and item.delete|default(False)
  tags: ['vhosts']

- name: vhosts | unlink letsencrypt cert directory
  file: path=/etc/ssl/{{ item.url }} state=absent
  with_items: "{{ vhosts }}"
  when: item.ssl|default(False) == "letsencrypt" and item.delete|default(False)
  tags: ['vhosts']

- name: vhosts | disable site when it's not default
  file: path=/etc/apache2/sites-enabled/{{ item.url }}.conf state=absent
  with_items: "{{ vhosts }}"
  when: not item.default|default(False) and item.delete|default(False)
  notify: reload apache2
  tags: ['vhosts']

- name: vhosts | disable site as default
  file: path=/etc/apache2/sites-enabled/001-default.conf state=absent
  with_items: "{{ vhosts }}"
  notify: reload apache2
  when: item.default|default(False) and item.delete|default(False)
  tags: ['vhosts']

- name: vhosts | remove extras file
  file: path=/etc/apache2/extra.d/extra.{{ item.url }}.conf state=absent
  with_items: "{{ vhosts }}"
  when: item.delete|default(False)
  tags: ['vhosts']

- name: vhosts | remove vhost
  file: path=/etc/apache2/sites-available/{{ item.url }}.conf state=absent
  with_items: "{{ vhosts }}"
  when: item.delete|default(False)
  notify: reload apache2
  tags: ['vhosts']

# Only delete apache and ssl contents here, all the subdirs and files created for vhosts logs and data will be removed by removing the basedir
