---
- name: install munin
  apt:
    name: munin
    state: present
    cache_valid_time: "3600"
    update_cache: true

- name: create munin dotssh
  file:
    dest: ~munin/.ssh
    owner: munin
    group: munin
    mode: "0700"
    state: directory

- name: copy over private key for munin-checks over ssh
  template:
    src: id_rsa_munin.j2
    dest: ~munin/.ssh/id_rsa
    owner: munin
    group: munin
    mode: "0600"

- name: place munin-config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/munin/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - apache.conf
    - munin.conf
  notify: restart apache2

- name: link apache-munin to apache
  file:
    src: /etc/munin/apache.conf
    dest: /etc/apache2/conf-available/munin.conf
    state: link
  notify: restart apache2

- name: enable munin
  command: a2enconf munin
  args:
    creates: /etc/apache2/conf-enabled/munin.conf
