---
backup_required: True

borg_version: "1.0.7"
borg_checksum: "sha256:e1b5370bc55ce00eecbac459bc9751b540d48b7ba42168ad4e4505db175aa471"
borg_download_url: "https://github.com/borgbackup/borg/releases/download/{{ borg_version }}/borg-linux64"

borg_user: "borgbackup"
borg_group: "borgbackup"
borg_home: "/var/backup"
borg_pool: "{{ borg_home }}/repos"

backup_pre_commands:
  - '[[ ! -f "/usr/sbin/automysqlbackup" ]] || /usr/sbin/automysqlbackup'
  - "dpkg --get-selections > /root/.installed-software.log"

backup_include:
  - "/etc"
  - "/home"
  - "/root"
  - "/var/www"
  - "/var/log"

retention:
  hourly: 12
  daily: 7
  weekly: 4
  monthly: 6
  yearly: 1
