---

- import_tasks: postfix.yml

- import_tasks: php.yml

- import_tasks: mysql.yml
  when: databases is defined

- import_tasks: varnish.yml
  when: varnish_required == True

- import_tasks: solr.yml
  when: solr_required == True and solr_cores is defined

- import_tasks: apache.yml
  when: vhosts is defined

- import_tasks: memcached.yml
  when: memcached_required == True

- import_tasks: redis.yml
  when: redis_required == True

- import_tasks: nginx.yml
  when: nginx_required | default(False) == True
