---

- include: postfix.yml

- include: php.yml

- include: mysql.yml
  when: databases is defined

- include: varnish.yml
  when: varnish_required == True

- include: solr.yml
  when: solr_required == True and solr_cores is defined

- include: apache.yml
  when: vhosts is defined

- include: memcached.yml
  when: memcached_required == True

- include: redis.yml
  when: redis_required == True

- include: nginx.yml
  when: nginx_required | default(False) == True
