---
- name: install requirements for redis-check
  apt: name=libredis-perl state=installed

- name: place check_redis.pl
  copy: src=redis/check_redis.pl dest=/usr/lib/nagios/plugins/check_redis.pl mode=0755 owner=root group=root

# TODO
#- name: place check_mk script for redis
#  template: src=redis/check_redis.j2 dest=/usr/lib/check_mk_agent/local/check_redis mode=0755 owner=root group=root
#  notify: inventory the new host
