---
- name: enable surey repo
  include_tasks: repo.yml
  when: php7_version != "7.0"

- name: install default required php packages | {{ php7_version }}
  apt:
    name: "php{{ php7_version }}-{{ item }}"
    state: installed
    cache_valid_time: 3600
    update_cache: yes
  with_items:
    - "{{ php_default_pkgs }}"

- name: install php 7.0 only packages
  apt:
    name: "{{ item }}"
    state: installed
    cache_valid_time: 3600
    update_cache: yes
  when: php7_version == "7.0"
  with_items:
    - php-pear
    - php-imagick
    - php-uploadprogress
    - php-mcrypt

- name: install extra required packages
  apt:
    name: "{{ item }}"
    state: installed
    cache_valid_time: 3600
    update_cache: yes
  with_items: 
    - "{{ php_extra_pkg }}"

- name: put php.ini | {{ php7_version }}
  template:
    src: php.ini.j2
    dest: "/etc/php/{{ php7_version }}/fpm/php.ini"
    owner: root
    group: root
    mode: "0644"
  notify: reload php

- name: put php-fpm.conf | {{ php7_version }}
  template:
    src: php-fpm.conf.j2
    dest: "/etc/php/{{ php7_version }}/fpm/php-fpm.conf"
    owner: root
    group: root
    mode: "0644"
  notify: reload php

- name: put www-data pool config-file | {{ php7_version }}
  template:
    src: www.conf.j2
    dest: "/etc/php/{{ php7_version }}/fpm/pool.d/www.conf"
    owner: root
    group: root
    mode: "0644"
  notify: restart php

- name: make sure libapache2-mod-php{{ php7_version }} is not installed, use fpm!
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - "libapache2-mod-php{{ php7_version }}"
    - libapache2-mod-php
  notify: restart apache2
