# -*- mode: ruby -*-
# vi: set ft=ruby :
#

#DEBIAN9_BOX = "debian94"
#DEBIAN9_BOX_URL = "http://delta.exabyte.be/vagrant-boxes/debian-9.4-amd64.box"
DEBIAN10_BOX = "debian/buster64"
#DEBIAN10_BOX_URL = "http://delta.exabyte.be/vagrant-boxes/debian-10.2-amd64.box"

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end

  config.ssh.insert_key = false

  config.vm.define "fiaas01" do |v|
    v.vm.box = DEBIAN10_BOX
    v.vm.hostname = "fiaas01"
    v.vm.network :private_network, ip: "192.168.131.190"
    v.vm.network :forwarded_port, guest: 22, host: 2163, id: 'ssh'
    v.vm.provision :ansible do |ansible|
      ansible.inventory_path = "inventory/"
      ansible.playbook = "../../playbooks/lamp.yml"
      ansible.host_key_checking = "false"
      ansible.limit = 'all'
    end
  end
end

