# -*- mode: ruby -*-
# vi: set ft=ruby :
#

DEBIAN10_BOX = "debian/buster64"
DEBIAN11_BOX = "debian/bullseye64"
DEBIAN12_BOX = "debian/bookworm64"

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end

  config.ssh.insert_key = false
  config.ssh.private_key_path = [ "~/.vagrant.d/insecure_private_key" ]

  config.vm.define "fiaas01" do |v|
    v.vm.box = DEBIAN12_BOX
    v.vm.hostname = "fiaas01"
    v.vm.network :private_network, ip: "192.168.131.190"
    v.vm.network :forwarded_port, guest: 22, host: 2163, id: 'ssh'
    v.vm.provision :ansible do |ansible|
      ansible.inventory_path = "inventory/"
      ansible.playbook = "../../playbooks/lamp.yml"
      ansible.host_key_checking = "false"
      ansible.verbose = "v"
      ansible.limit = 'all'
    end
  end
end

