---
- name: Copy custom plugins to clients
  copy:
    src: "{{ item }}"
    dest: "{{ monitoring_plugins_path }}/"
    owner: root
    group: root
    mode: "0775"
  with_fileglob:
    - plugins/*

- name: Configure sudo access for event handlers
  template:
    src: icinga-sudo.j2
    dest: /etc/sudoers.d/icinga
    owner: root
    group: root
    mode: "0440"
    validate: visudo -cf %s
