---
- name: Converge
  hosts: all
  become: yes
  pre_tasks:
    - include_vars: "../../../../os_vars/{{ ansible_distribution_release }}.yml"
      tags: ['always']
    - apt: update_cache=yes cache_valid_time=3600
  roles:
    - role: createresources

