---
- name: drupal | make sure the Drush Debian package is absent
  apt:
    name: drush
    state: absent
    cache_valid_time: 3600
    update_cache: yes

- stat:
    path: /etc/cron.d/drupal
  register: drupal_cron

- name: drupal | put /etc/cron.d/drupal example if the file doesn't exist
  copy:
    src: cron-drupal
    dest: /etc/cron.d/drupal
    owner: root
    group: root
    mode: "0644"
  when: drupal_cron.stat.exists == False
