---
# WARNING: some functions in this role can be harmfull for your system
# Eg www-data shell and cron sudo are meant for trusted developers on a private server

- import_tasks: phptools.yml

- import_tasks: drupal.yml

# warning: don't install phpmyadmin before php-fpm or you'll get mod-php with it!
# no phpmyadmin in buster, skip for now
- import_tasks: phpmyadmin.yml
  when: >
    ansible_distribution == 'Debian'
    and ansible_distribution_major_version is version('10', '<')

- import_tasks: composer.yml

- import_tasks: drush_launcher.yml
