---
# WARNING: some functions in this role can be harmfull for your system
# Eg www-data shell and cron sudo are meant for trusted developers on a private server

- import_tasks: phptools.yml

- import_tasks: drupal.yml

# warning: don't install phpmyadmin before php-fpm or you'll get mod-php with it!
- import_tasks: phpmyadmin.yml

- import_tasks: composer.yml
