---
- name: phptools | install extra packages
  apt:
    name: "{{ phptools_pkgs }}"
    state: present
    cache_valid_time: 3600
    update_cache: yes

- name: phptools | copy www-data-shell.sh script
  copy:
    src: www-data-shell.sh
    dest: /usr/local/bin/www-data-shell
    owner: root
    group: root
    mode: "0755"
