---
scenario:
  name: fiaas01-debian8
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: fiaas01
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.131.190
    box: debian82
    box_url: http://repo.werus.be/vagrant/debian-8.2-amd64.box
    memory: 1024
    cpus: 1
    provider_options:
      gui: False
provisioner:
  name: ansible
  inventory:
    links:
      host_vars: ../../../../../vagrant/vagrant/inventory/host_vars/
      group_vars: ../../../../../vagrant/vagrant/inventory/group_vars/
verifier:
  name: testinfra
  lint:
    name: flake8
