---

- include: install.yml
  when: backup_required == True or inventory_hostname in groups.backupservers or restore == True

- include: borg-server.yml
  when: inventory_hostname in groups.backupservers

- include: borg-client.yml
  when: backup_required == True and inventory_hostname not in groups.backupservers

- include: restore.yml
  when: restore == True and inventory_hostname not in groups.backupservers
