- name: Configure monitored hosts
  hosts: all:!backupservers
  become: True

  pre_tasks:
    - include_vars: "./os_vars/{{ ansible_distribution_release }}.yml"
      tags: ['backup']
    - apt: update_cache=yes cache_valid_time=3600

  roles:
    - system
    - role: borgbackup
      tags: ['backup']
