---
- name: Configure backups
  hosts: backup:!borgbackup_servers
  become: true

  pre_tasks:
    - apt:
        update_cache: true
        cache_valid_time: '3600'

  roles:
    - role: system
    - role: fiaasco.borgbackup
      tags: ['backup']
