---
- name: Remove resources
  hosts: all:!infra
  become: True

  pre_tasks:
    - include_vars: "./os_vars/{{ ansible_distribution_release }}.yml"
      tags: ['always']

  roles:
    - role: removeresources
    - role: readme
