---
- hosts: all
  gather_facts: False
  sudo: False

  pre_tasks:
    - include_vars: "./../inventory/{{ platform }}/group_vars/{{ item }}.yml"
      with_items:
        - owners
    - include_vars: "./../playbooks/roles/backup/defaults/main.yml"

  roles:
    - docu
