---
- name: icinga2 setup
  hosts: icingaservers
  become: True

  pre_tasks:
    - apt:
        update_cache: true
        cache_valid_time: '3600'

  roles:
    - fail2ban
    - role: users
      tags: ['users']
    - ufw
    - ntp
    - postfix
    - system
    - role: httpd
      tags: ['httpd']
    - role: fastcgi
      tags: ['php','httpd']
    - role: letsencrypt
      tags: ['letsencrypt', 'acme']
    - role: php7
      tags: ['php']
    - role: mariadb
      tags: ['mysql', 'mariadb']
    - role: icinga/prepare
      tags: ['icinga']
    - role: icinga/master
      tags: ['icinga']
    - role: icinga/hostconfig
      tags: ['icinga', 'hostconfig']
    - role: icinga/icingaweb
      tags: ['icinga', 'icingaweb']
    - role: icinga/checks
      tags: ['icinga', 'checks']
