---
- name: Install LAMP env.
  hosts: all
  become: true

  pre_tasks:
    - apt:
        update_cache: true
        cache_valid_time: '3600'

  roles:
#    - role: fiaasco.fail2ban
#      tags: ['fail2ban']
    - role: fiaasco.lamp.sshguard
      tags:
        - sshguard
    - role: system
      tags: ['system']
    - role: users
      tags: ['users']
    - role: ufw
      tags: ['ufw']
    - role: fiaasco.chrony
      tags: ['ntp']
    - role: fiaasco.postfix
      tags: ['postfix']

- hosts: swapfile
  become: true
  roles:
    - role: fiaasco.lamp.swap
      tags:
        - swap
        - swapfile

- hosts: opendkim
  become: true
  roles:
    - role: fiaasco.opendkim
      tags: ['opendkim']

- hosts: httpd
  become: true
  roles:
    - role: letsencrypt
      tags: ['letsencrypt', 'acme']
#    - role: fiaasco.apache2
    - role: httpd
      tags: ['httpd']

- hosts: varnish
  become: true
  roles:
    - role: varnish
      tags: ['varnish']

- hosts: nginx
  become: true
  roles:
    - role: nginx
      tags: ['nginx']

- hosts: mysql
  become: true
  roles:
    - role: fiaasco.mariadb
      tags: ['mysql', 'mariadb']

- hosts: php7
  become: true
  roles:
    - role: fastcgi
      tags: ['php', 'httpd']
    - role: fiaasco.php7
      tags: ['php']
    - role: phpdevtools
      tags: ['phpdevtools']

- hosts: php8
  become: true
  roles:
    - role: fastcgi
      tags: ['php8', 'php', 'httpd']
    - role: fiaasco.php8
      tags: ['php8', 'php']
    - role: phpdevtools
      tags: ['phpdevtools']

- hosts: solr
  become: true
  roles:
    - role: solr-multicore
      tags: ['solr']

- hosts: solr8
  become: true
  roles:
    - role: fiaasco.solr
      tags: ['solr', 'solr8']

- hosts: redis
  become: true
  roles:
    - role: redis
      tags: ['redis']

- hosts: memcached
  become: true
  roles:
    - role: memcached
      tags: ['memcached']

- hosts: vsftpd
  become: true
  roles:
    - role: vsftpd
      tags: ['vsftpd']
