---
- name: Install LAMP env.
  hosts: all:!infra
  become: True

  pre_tasks:
    - apt:
        update_cache: true
        cache_valid_time: '3600'

  roles:
    - role: locale
      tags: ['locale']
    - role: fail2ban
      tags: ['fail2ban']
    - role: system
      tags: ['system']
    - role: users
      tags: ['users']
    - role: ufw
      tags: ['ufw']
    - role: ntp
      tags: ['ntp']
    - role: postfix
      tags: ['postfix']
    - role: letsencrypt
      tags: ['letsencrypt', 'acme']
    - role: httpd
      tags: ['httpd']
    - role: varnish
      tags: ['varnish']
    - role: nginx
      tags: ['nginx']
    - role: fastcgi
      tags: ['php', 'httpd']
    - role: mariadb
      tags: ['mysql', 'mariadb']
    - role: php7
      tags: ['php']
    - role: phpdevtools
      tags: ['phpdevtools']
    - role: solr-multicore
      tags: ['solr']
    - role: redis
      tags: ['redis']
    - role: memcached
      tags: ['memcached']
    - role: vsftpd
      tags: ['vsftpd']
