---
- name: Install LAMP env.
  hosts: all
  become: true

  pre_tasks:
    - apt:
        update_cache: true
        cache_valid_time: '3600'

  roles:
    - role: locale
      tags: ['locale']
    - role: fail2ban
      tags: ['fail2ban']
    - role: system
      tags: ['system']
    - role: users
      tags: ['users']
    - role: ufw
      tags: ['ufw']
    - role: fiaasco.chrony
      tags: ['ntp']
    - role: postfix
      tags: ['postfix']

- hosts: httpd
  become: true
  roles:
    - role: letsencrypt
      tags: ['letsencrypt', 'acme']
    - role: httpd
      tags: ['httpd']

- hosts: varnish
  become: true
  roles:
    - role: varnish
      tags: ['varnish']

- hosts: nginx
  become: true
  roles:
    - role: nginx
      tags: ['nginx']

- hosts: mysql
  become: true
  roles:
    - role: mariadb
      tags: ['mysql', 'mariadb']

- hosts: php7
  become: true
  roles:
    - role: fastcgi
      tags: ['php', 'httpd']
    - role: php7
      tags: ['php']
    - role: phpdevtools
      tags: ['phpdevtools']

- hosts: solr
  become: true
  roles:
    - role: solr-multicore
      tags: ['solr']

- hosts: redis
  become: true
  roles:
    - role: redis
      tags: ['redis']

- hosts: memcached
  become: true
  roles:
    - role: memcached
      tags: ['memcached']

- hosts: vsftpd
  become: true
  roles:
    - role: vsftpd
      tags: ['vsftpd']
