---
- name: Configure monitored hosts
  hosts: all:!icinga2master
  become: True
  collections:
   - fiaasco.icinga2

  pre_tasks:
    - apt:
        update_cache: true
        cache_valid_time: '3600'

  roles:
    - role: icinga2_client
      tags:
        - icinga
        - client
    - role: icinga2_hostconfig
      tags:
        - icinga
        - hostconfig
    - role: munin-node
      tags:
        - munin
        - monitoring
    - role: monitoring_plugins
      tags:
        - munin
        - monitoring
