- name: Configure monitored hosts
  hosts: all:!icingaservers
  become: True

  pre_tasks:
    - include_vars: "./os_vars/{{ ansible_distribution_release }}.yml"
      tags: ['backup']
    - apt: update_cache=yes cache_valid_time=3600

  roles:
    - role: icinga-client
      tags: ['icinga', 'monitoring']
    - role: munin-plugins
      tags: ['munin', 'monitoring']
