---
- name: Configure monitored hosts
  hosts: all:!icingaservers
  become: True

  pre_tasks:
    - apt:
        update_cache: true
        cache_valid_time: '3600'

  roles:
    - role: icinga/prepare
      tags: ['icinga', 'prepare']
    - role: icinga/client
      tags: ['icinga', 'client']
    - role: icinga/hostconfig
      tags: ['icinga', 'hostconfig']
    - role: munin-node
      tags: ['munin', 'monitoring']
    - role: munin-plugins
      tags: ['munin', 'monitoring']
