---
- name: Munin server setup
  hosts: muninservers
  become: True

  pre_tasks:
    - apt:
        update_cache: true
        cache_valid_time: '3600'

  roles:
    - fail2ban
    - role: users
      tags: ['users']
    - ufw
    - ntp
    - postfix
    - system
    - role: munin
      tags: ['monitoring']
    - role: httpd
      tags: ['httpd']
    - role: letsencrypt
      tags: ['letsencrypt', 'acme']
    - role: munin-node
      tags: ['monitoring']
