---
- name: Munin server setup
  hosts: muninservers
  become: True

  pre_tasks:
    - include_vars: "./os_vars/{{ ansible_distribution_release }}.yml"
      tags: ['always']
    - apt: update_cache=yes cache_valid_time=3600

  roles:
    - fail2ban
    - role: users
      tags: ['users']
    - ufw
    - ntp
    - postfix
    - system
    - role: munin
      tags: ['monitoring']
    - role: httpd
      tags: ['httpd']
    - role: letsencrypt
      tags: ['letsencrypt', 'acme']
    - role: munin-node
      tags: ['monitoring']
    - role: borgbackup
      tags: ['backup']
