- name: Install LAMP env.
  hosts: all:!infra
  become: True
  become_method: sudo

  pre_tasks:
    - include_vars: "./os_vars/{{ ansible_distribution_release }}.yml"
      tags: ['always']
    - include_vars: "./../inventory/{{ platform }}/group_vars/{{ item }}"
      with_items:
        - owners

  roles:
    - role: removeresources
    - role: readme
