---
- name: Create resources and update monitoring
  hosts: all:!infra
  become: True
  pre_tasks:
    - include_vars: "./os_vars/{{ ansible_distribution_release }}.yml"
      tags: ['always']

  roles:
    - createresources
    - removeresources
    - readme
    - icinga/hostconfig
