- name: setup base env
  hosts: support
  become: True

  pre_tasks:
    - include_vars: "./os_vars/{{ ansible_distribution_release }}.yml"
      tags: ['varnish', 'httpd', 'php', 'resources']
    - include_vars: "./../inventory/{{ platform }}/group_vars/{{ item }}"
      with_items:
        - owners
      tags: ['resources','sshkeys']
    - apt: update_cache=yes cache_valid_time=3600

  roles:
    - role: fail2ban
      tags: ['fail2ban']
    - role: system
      tags: ['system']
    - role: users
      tags: ['users']
    - role: ufw
      tags: ['ufw']
    - ntp
    - postfix
