---
- name: install postfix
  apt:
    name:
      - postfix
      - mailutils
    state: present
    cache_valid_time: 3600
    update_cache: yes

- name: put mailname configuration
  template:
    src: mailname.j2
    dest: /etc/mailname
    owner: root
    group: root
    mode: "0644"

- name: test if certificate exists
  stat:
    path: "{{ postfix_certificate }}"
  register: cert_path

- name: put postfix configuration
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: "0644"
  notify: restart postfix
