---
- name: install postfix
  apt:
    name:
      - postfix
      - mailutils
    state: present
    cache_valid_time: 3600
    update_cache: yes

- name: put postfix configuration
  template:
    src: mailname.j2
    dest: /etc/mailname
    owner: root
    group: root
    mode: "0644"
  with_items:
    - mailname.j2
    - main.cf.j2
  notify: restart postfix
