---
- name: system | set vim.tiny as default editor
  alternatives: name=editor path=/usr/bin/vim.tiny

- include: hostname.yml

- include: packages.yml

- include: vm-tools.yml

- include: limits.yml

- include: sysctl.yml

- include: extras.yml
