---
- name: install extra packages
  apt:
    name:
      - acl
      - atop
      - curl
      - dstat
      - lsof
      - rsync
      - sudo
      - sysstat
      - unzip
      - vim
      - zip
      - bzip2
      - gnupg
    state: present
    cache_valid_time: 3600
    update_cache: yes
