---
- name: install extra packages
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
    update_cache: yes
  with_items:
    - acl
    - atop
    - curl
    - dstat
    - lsof
    - rsync
    - sudo
    - sysstat
    - unzip
    - vim
    - zip
    - bzip2
