---
- name: security | configure sshd root logins
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin "
    line: "PermitRootLogin {{ system_ssh_rootlogin }}"
  notify: reload ssh

- name: security | remove sshd weak hostkeys
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "HostKey {{ item }}"
    state: absent
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version >= '8'
  with_items:
    - /etc/ssh/ssh_host_dsa_key
    - /etc/ssh/ssh_host_ecdsa_key
  notify: reload ssh

- name: security | configure strong sshd key exchange algoritms
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^KexAlgorithms "
    line: "KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256"
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version >= '8'
  notify: reload ssh

- name: security | remove insecure moduli
  lineinfile:
    dest: /etc/ssh/moduli
    regexp: "\ {{ item }}\ "
    state: absent
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version >= '8'
  with_items:
    - "1023"
    - "1535"
    - "2047"
  notify: reload ssh

- name: security | configure strong sshd ciphers
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Ciphers "
    line: "Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version >= '8'
  notify: reload ssh

- name: security | configure strong sshd MACs
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^MACs "
    line: "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com"
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version >= '8'
  notify: reload ssh

- name: security | log sftp file access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^Subsystem\s+sftp\s+/usr/lib/openssh/sftp-server'
    line: "Subsystem       sftp    /usr/lib/openssh/sftp-server -f AUTHPRIV -l INFO"
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version >= '8'
  notify: reload ssh
